### ISSUE TITLE
Crash on load Blade and Sorcery bundles

### ISSUE THREAD

**Issue by Greenf1re** [ds5678/AssetRipper#1]
Game name: Blade & Sorcery U9.3
Engine version: 2019.4
Platform: PC/VR
Error message: Read 24 but expected 7993

Stack trace:    at AssetRipper.BundleFileScheme.ReadMetadata(Stream stream, Int32 metadataSize)
   at AssetRipper.BundleFileScheme.ReadFileStreamMetadata(Stream stream, Int64 basePosition)
   at AssetRipper.BundleFileScheme.ReadScheme(Stream stream)
   at AssetRipper.BundleFileScheme.ReadScheme(Stream stream, String filePath, String fileName)
   at AssetRipper.BundleFile.ReadScheme(Stream stream, String filePath, String fileName)
   at AssetRipper.GameCollection.ReadScheme(SmartStream stream, String filePath, String fileName)
   at AssetRipper.GameCollection.LoadScheme(String filePath, String fileName)
   at AssetRipper.GameStructure.ProcessPlatformStructure(GameStructureProcessor processor, PlatformGameStructure structure)
   at AssetRipper.GameStructure.Load(List`1 pathes, LayoutInfo layinfo)
   at AssetRipper.GameStructure.Load(IEnumerable`1 pathes, LayoutInfo layinfo)
   at AssetRipper.GameStructure.Load(IEnumerable`1 pathes)
   at AssetRipperGUI.MainWindow.LoadFiles(Object data)

**Comment by ds5678** [comment]
I'm not familiar with this game. Did the program work for you on other games?

Also, I'm currently working on cleaning up the project. In my next release, I want to implement an improved logging system so people can give better bug reports.

**Comment by Greenf1re** [comment]
> I'm not familiar with this game. Did the program work for you on other games?
Yes, it works on other Unity games I have.
> Also, I'm currently working on cleaning up the project and doing other small quality of life changes. In my next release, I want to implement an improved logging system. Then, people could include their log when making a bug report.
Sounds good, can't wait to see the improbements.

**Comment by ds5678** [comment]
I just released [0.1.1.0](https://github.com/ds5678/AssetRipper/releases/tag/0.1.1.0), which includes file logging. Can you please retry this and upload `AssetRipper.log`?

**Comment by Greenf1re** [comment]
Ok, I tried it again with the new version, this is the log.
[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/6845222/AssetRipper.log)

**Comment by ds5678** [comment]
Can you shoot me an email or twitter message, so we can discuss what you're trying to do?

**Comment by ds5678** [comment]
Can you try loading your asset bundle with [AssetStudio](https://github.com/Perfare/AssetStudio)? That would confirm or deny my Addressable theory.

**Comment by Greenf1re** [comment]
AssetStudio does load and export fine, but for what I wanted to do I'd neet AssetRipper. The game does use the addressable system, there is a public [SDK](https://github.com/KospY/BasSDK) for mod makers if you want to take a look.

**Comment by ds5678** [comment]
Yeah, it's a problem with Addressables. They are the main barrier to 2020+ support.

**Comment by ds5678** [comment]
I've posted and pinned an [issue](#5 ) describing this problem, so I'm going to close this issue.
