### ISSUE TITLE
[Bug]: Culture Error 

### ISSUE THREAD

**Issue by emre1601** [ds5678/AssetRipper#13]
### Are you on the latest version of AssetRipper?

- [X] Yes, I'm on the latest version of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

no games, when the program is first started

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

![image](https://user-images.githubusercontent.com/31389427/127218534-3d108c86-27e9-4ead-941b-aebe3271c7d2.png)

When I click on the console output here or the text output in the bug report, the program freezes and crashes.

![image](https://user-images.githubusercontent.com/31389427/127218809-01ee2876-5e56-4d50-9a81-713618d28d13.png)

When I open the project file and click on the output part, it gives a culture error like this.
![image](https://user-images.githubusercontent.com/31389427/127218341-3a06f4cb-e114-4156-833a-5858e85e7c96.png)

### Relevant log output

The log file does not exist, because the program crashes immediately.

**Comment by ds5678** [comment]
How does your computer not support the invariant culture?

**Comment by emre1601** [comment]
I have no idea, my language is Turkish by the way. Is this problem related to my computer?

**Comment by ds5678** [comment]
Maybe, try it on a few other computers. I am hesitant to deviate from the invariant culture because it ensures readable stack traces and correct numeric parsing.

**Comment by ds5678** [comment]
Also, try the console version. It works just as well as the GUI version.

**Comment by emre1601** [comment]
no problem as long as i don't just click the output below :)

**Comment by ds5678** [comment]
This just got way more interesting. I have the same issue. I'm going to look into this.

**Comment by ds5678** [comment]
I removed the culture modifier in the GUI project. That fixed it for me. I want to know if it fixed it for you too and if stack traces are now localized.

**Comment by emre1601** [comment]
> I removed the culture modifier in the GUI project. That fixed it for me. I want to know if it fixed it for you too and if stack traces are now localized.

Because of the translation, I guess I didn't quite understand, but I think you removed the culture, I think I'll download and try it right away.

**Comment by emre1601** [comment]
yes it's ok now, click on output and everything works as it should. ✨✨

**Comment by ds5678** [comment]
Make it error, I want to see a stack trace

**Comment by emre1601** [comment]
How do I do when I say make a mistake, the error in the culture part has already been solved, but this error continues
![image](https://user-images.githubusercontent.com/31389427/127248832-ee27dedd-49ea-4270-913a-4bfc7c0bd95e.png)
[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/6889661/AssetRipper.log)

**Comment by ds5678** [comment]
This is an asset bundle I made for Unity `2020.2.0`. Can you extract its contents and then drop the `unity3d` file into the GUI and send me the stack trace?
[data.zip](https://github.com/ds5678/AssetRipper/files/6889672/data.zip)

**Comment by emre1601** [comment]
![image](https://user-images.githubusercontent.com/31389427/127249454-0a92431e-ec91-4408-ba1d-475da98b9e70.png)
![image](https://user-images.githubusercontent.com/31389427/127249557-a15be25e-67ae-4fa0-9ae6-9fdcdba5dd8b.png)
**### ERROR DETAİLS**
```
System.Exception
  HResult=0x80131500
  İleti=Some data left
  Kaynak=AssetRipperCore
  StackTrace:
   at AssetRipper.Lz4.Lz4DecodeStream.ReadBuffer(Stream stream, Int64 count) in C:\Users\Emre\Downloads\AssetRipper-master\AssetRipper-master\AssetRipperCore\Lz4\Lz4DecodeStream.cs:line 227
   at AssetRipper.Parser.Files.BundleFile.BundleFileScheme.ReadFileStreamMetadata(Stream stream, Int64 basePosition) in C:\Users\Emre\Downloads\AssetRipper-master\AssetRipper-master\AssetRipperCore\Parser\Files\BundleFile\BundleFileScheme.cs:line 157
   at AssetRipper.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream) in C:\Users\Emre\Downloads\AssetRipper-master\AssetRipper-master\AssetRipperCore\Parser\Files\BundleFile\BundleFileScheme.cs:line 63
   at AssetRipper.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream, String filePath, String fileName) in C:\Users\Emre\Downloads\AssetRipper-master\AssetRipper-master\AssetRipperCore\Parser\Files\BundleFile\BundleFileScheme.cs:line 34
   at AssetRipper.Parser.Files.BundleFile.BundleFile.ReadScheme(Stream stream, String filePath, String fileName) in C:\Users\Emre\Downloads\AssetRipper-master\AssetRipper-master\AssetRipperCore\Parser\Files\BundleFile\BundleFile.cs:line 64
   at AssetRipper.Structure.GameCollection.ReadScheme(SmartStream stream, String filePath, String fileName) in C:\Users\Emre\Downloads\AssetRipper-master\AssetRipper-master\AssetRipperCore\Structure\GameCollection.cs:line 118
   at AssetRipper.Structure.GameCollection.LoadScheme(String filePath, String fileName) in C:\Users\Emre\Downloads\AssetRipper-master\AssetRipper-master\AssetRipperCore\Structure\GameCollection.cs:line 86
   at AssetRipper.Structure.GameStructure.GameStructureProcessor.AddScheme(String filePath, String fileName) in C:\Users\Emre\Downloads\AssetRipper-master\AssetRipper-master\AssetRipperCore\Structure\GameStructure\GameStructureProcessor.cs:line 28
   at AssetRipper.Structure.GameStructure.GameStructure.ProcessPlatformStructure(GameStructureProcessor processor, PlatformGameStructure structure) in C:\Users\Emre\Downloads\AssetRipper-master\AssetRipper-master\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 178
   at AssetRipper.Structure.GameStructure.GameStructure.Load(List`1 paths, LayoutInfo layinfo) in C:\Users\Emre\Downloads\AssetRipper-master\AssetRipper-master\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 59
   at AssetRipper.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, LayoutInfo layinfo) in C:\Users\Emre\Downloads\AssetRipper-master\AssetRipper-master\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 37
   at AssetRipper.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths) in C:\Users\Emre\Downloads\AssetRipper-master\AssetRipper-master\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 26
   at AssetRipperGUI.MainWindow.LoadFiles(Object data) in C:\Users\Emre\Downloads\AssetRipper-master\AssetRipper-master\AssetRipperGUI\MainWindow.xaml.cs:line 95
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

```

**### ASSET Ripper Log File Content:** 
```
Import : Game file 'data.unity3d' has been found
Import : Mixed game structure has been found for 1 path(s)
```

**Comment by ds5678** [comment]
And what's it look like if you drop it into uTinyRipper instead?

**Comment by emre1601** [comment]
**### Crash Window Content:**

```
Game name: (please, specify the game name)
Engine version: (specify engine version, if known)
Platform: (specify platform, if known)

Error message: Some data left

Stack trace:    konum: uTinyRipper.Lz4.Lz4DecodeStream.ReadBuffer(Stream stream, Int64 count)
   konum: uTinyRipper.BundleFileScheme.ReadFileStreamMetadata(Stream stream, Int64 basePosition)
   konum: uTinyRipper.BundleFileScheme.ReadScheme(Stream stream)
   konum: uTinyRipper.GameCollection.ReadScheme(SmartStream stream, String filePath, String fileName)
   konum: uTinyRipper.GameCollection.LoadScheme(String filePath, String fileName)
   konum: uTinyRipper.GameStructure.ProcessPlatformStructure(GameStructureProcessor processor, PlatformGameStructure structure)
   konum: uTinyRipper.GameStructure.Load(List`1 pathes, LayoutInfo layinfo)
   konum: uTinyRipper.GameStructure.Load(IEnumerable`1 pathes, LayoutInfo layinfo)
   konum: uTinyRipperGUI.MainWindow.LoadFiles(Object data)
```

### **Log Output:**
```
Import: Game file 'data.unity3d' has been found
Import [Error]: System.Exception: Some data left
   konum: uTinyRipper.Lz4.Lz4DecodeStream.ReadBuffer(Stream stream, Int64 count)
   konum: uTinyRipper.BundleFileScheme.ReadFileStreamMetadata(Stream stream, Int64 basePosition)
   konum: uTinyRipper.BundleFileScheme.ReadScheme(Stream stream)
   konum: uTinyRipper.GameCollection.ReadScheme(SmartStream stream, String filePath, String fileName)
   konum: uTinyRipper.GameCollection.LoadScheme(String filePath, String fileName)
   konum: uTinyRipper.GameStructure.ProcessPlatformStructure(GameStructureProcessor processor, PlatformGameStructure structure)
   konum: uTinyRipper.GameStructure.Load(List`1 pathes, LayoutInfo layinfo)
   konum: uTinyRipper.GameStructure.Load(IEnumerable`1 pathes, LayoutInfo layinfo)
   konum: uTinyRipperGUI.MainWindow.LoadFiles(Object data)

```

**Comment by ds5678** [comment]
Perfect!

**Comment by ds5678** [comment]
Stack traces in AssetRipper are still invariant, and the clicking issue is solved

**Comment by ds5678** [comment]
So my commit made everything work correctly for you?

**Comment by ds5678** [comment]
Unless you have any objections, I'm going to close this
