### ISSUE TITLE
[Bug]: SerializedFile with index ______ was not found in dependencies

### ISSUE THREAD

**Issue by BTELNYY** [ds5678/AssetRipper#145]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2017.3.of3

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Decompiling works, but when I attempt to export the game it fails.  Something about dependencies?

### Relevant log output

4:48:09 PM: [Error] : System.Exception: SerializedFile with index 842019116 was not found in dependencies
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.FindAsset(Int32 fileIndex, Int64 pathID, Boolean isSafe) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Parser/Files/SerializedFile/SerializedFile.cs:line 271
   at AssetRipper.Core.Project.ProjectAssetContainer.FindAsset(Int32 fileIndex, Int64 pathID) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Project/ProjectAssetContainer.cs:line 109
   at AssetRipper.Core.Classes.Misc.PPtr`1.FindAsset(IAssetContainer file) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Classes/Misc/PPtr.cs:line 106
   at AssetRipper.Core.Classes.Misc.PPtr`1.ExportYAML(IExportContainer container) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Classes/Misc/PPtr.cs:line 86
   at AssetRipper.Core.Structure.Assembly.Serializable.SerializableField.ExportYAML(IExportContainer container, Field& etalon) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/Assembly/Serializable/SerializableField.cs:line 492
   at AssetRipper.Core.Structure.Assembly.Serializable.SerializableStructure.ExportYAML(IExportContainer container) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/Assembly/Serializable/SerializableStructure.cs:line 49
   at AssetRipper.Core.Structure.Assembly.Serializable.SerializableField.ExportYAML(IExportContainer container, Field& etalon) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/Assembly/Serializable/SerializableField.cs:line 492
   at AssetRipper.Core.Structure.Assembly.Serializable.SerializableStructure.ExportYAML(IExportContainer container) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/Assembly/Serializable/SerializableStructure.cs:line 49
   at AssetRipper.Core.Classes.MonoBehaviour.ExportYAMLRoot(IExportContainer container) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Classes/MonoBehaviour.cs:line 87
   at AssetRipper.Core.Classes.Object.Object.ExportYAMLDocument(IExportContainer container) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Classes/Object/Object.cs:line 71
   at AssetRipper.Core.Project.Exporters.YAMLAssetExporter.Export(IExportContainer container, Object asset, String path) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Project/Exporters/YAMLAssetExporter.cs:line 38
   at AssetRipper.Core.Project.Collections.AssetExportCollection.Export(ProjectAssetContainer container, String dirPath) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Project/Collections/AssetExportCollection.cs:line 39
   at AssetRipper.Core.Project.ProjectExporter.Export(GameCollection fileCollection, IEnumerable`1 files, CoreConfiguration options) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Project/ProjectExporter.cs:line 265
   at AssetRipper.Core.Project.ProjectExporter.Export(GameCollection fileCollection, CoreConfiguration options) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Project/ProjectExporter.cs:line 185
   at AssetRipper.Core.Structure.GameCollection.Export(CoreConfiguration options) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/GameCollection.cs:line 98
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Export(CoreConfiguration options) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/GameStructure/GameStructure.cs:line 100
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, IEnumerable`1 assets) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperLibrary/Ripper.cs:line 116
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperLibrary/Ripper.cs:line 104
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperGUI/Managers/UIExportManager.cs:line 
[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7438299/AssetRipper.log)
46

**Comment by ds5678** [comment]
Closed in favor of #172
