### ISSUE TITLE
.unity3d file importing Error (Unturned game)

### ISSUE THREAD

**Issue by Ravenger2709** [ds5678/AssetRipper#16]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

With FMTV.unity3d model. I bundle it with Unity 2019.4.28f1

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

Error then i import .unity3d model.

https://drive.google.com/file/d/1SQe-BBjcTc7vSYlOJUzkpS1GqJj7f2ZN/view?usp=sharing model here

### Relevant log output

System: AssetRipper GUI Version
System: System Version: Microsoft Windows NT 10.0.19043.0
System: Operating System: Windows x64
System: AssetRipper Version: 0.1.3.1
System: AssetRipper Build Type: Release x64
System: AssetRipper Process: x64
Import: Game file 'FMTV.unity3d' has been found
Import: Mixed game structure has been found for 1 path(s)
Import [Error]: System.Exception: Read 24 but expected 219
   at AssetRipper.Parser.Files.BundleFile.BundleFileScheme.ReadMetadata(Stream stream, Int32 metadataSize)
   at AssetRipper.Parser.Files.BundleFile.BundleFileScheme.ReadFileStreamMetadata(Stream stream, Int64 basePosition)
   at AssetRipper.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream)
   at AssetRipper.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream, String filePath, String fileName)
   at AssetRipper.Parser.Files.BundleFile.BundleFile.ReadScheme(Stream stream, String filePath, String fileName)
   at AssetRipper.Structure.GameCollection.ReadScheme(SmartStream stream, String filePath, String fileName)
   at AssetRipper.Structure.GameCollection.LoadScheme(String filePath, String fileName)
   at AssetRipper.Structure.GameStructure.GameStructure.ProcessPlatformStructure(GameStructureProcessor processor, PlatformGameStructure structure)
   at AssetRipper.Structure.GameStructure.GameStructure.Load(List`1 paths, LayoutInfo layinfo)
   at AssetRipper.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, LayoutInfo layinfo)
   at AssetRipper.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths)
   at AssetRipperGUI.MainWindow.LoadFiles(Object data)

**Comment by ds5678** [comment]
Hi, this is a direct result of #5. Whenever I resolve that, this should be fixed

**Comment by CyberAndrii** [comment]
I've tried ripping the same asset bundle built using unity 2018.4 and 2019.4 and the first ripps successfully but the second one gives the same error as above.

btw the game doesn't use addressables.

**Comment by ds5678** [comment]
@CyberAndrii compile everything in release configuration. Then drop the bundle on the asset analyzer and send me the output.

**Comment by Ravenger2709** [comment]
Can u fix it bug?

**Comment by ds5678** [comment]
@Ravenger2709 probably but it's not something that can be fixed quickly

**Comment by Ravenger2709** [comment]
Thx you so much!

**Comment by CyberAndrii** [comment]
@ds5678 
```
BundleFile
Loading prophuntui.masterbundle
        Signature: UnityFS
        Bundle version: 6
        Unity version: 5.x.x
        Unity revision: 2018.4.13f1
        Sub Files:
                CAB-d8ebaf574a1303834b9e9f375258db58

```
```
BundleFile
Loading prophuntui.masterbundle
        Signature: UnityFS
        Bundle version: 7
        Unity version: 5.x.x
        Unity revision: 2019.4.28f1
        Sub Files:
                CAB-d8ebaf574a1303834b9e9f375258db58

```

**Comment by ds5678** [comment]
@CyberAndrii It is as I thought. You have the same issue as Ravenger. Your bundle version is now 7, which means it uses the new format.

**Comment by Ravenger2709** [comment]
@ds5678 Do u need any assets (for debugging and e.c.t.)?

**Comment by ds5678** [comment]
@Ravenger2709 I have the one from your initial post so, I don't need any others unless they have a different error.

**Comment by ds5678** [comment]
Hi, this should have been resolved in a recent commit. If your issue persists on the latest alpha build, please post a new issue.
