### ISSUE TITLE
Terminate the progress after an error is reported during export

### ISSUE THREAD

**Issue by dashenxiwo** [ds5678/AssetRipper#169]
### Describe the issue

14:35:12: : About to unpack unity crunch...
14:35:12: : About to unpack unity crunch...
14:35:12: : About to unpack unity crunch...
14:35:12: : About to unpack unity crunch...
14:35:12: [Error] : System.Exception: SerializedFile with index 5487 was not found in dependencies
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.FindAsset(Int32 fileIndex, Int64 pathID, Boolean isSafe) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 273
   at AssetRipper.Core.Project.ProjectAssetContainer.FindAsset(Int32 fileIndex, Int64 pathID) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Project\ProjectAssetContainer.cs:line 108
   at AssetRipper.Core.Classes.Misc.PPtr`1.FindAsset(IAssetContainer file) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Classes\Misc\PPtr.cs:line 107
   at AssetRipper.Core.Classes.Misc.PPtr`1.ExportYAML(IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Classes\Misc\PPtr.cs:line 87
   at AssetRipper.Core.IO.Extensions.IEnumerableYAMLExtensions.ExportYAML[T](IEnumerable`1 _this, IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Extensions\IEnumerableYAMLExtensions.cs:line 18
   at AssetRipper.Core.Structure.Assembly.Serializable.SerializableField.ExportYAML(IExportContainer container, Field& etalon) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\Assembly\Serializable\SerializableField.cs:line 492
   at AssetRipper.Core.Structure.Assembly.Serializable.SerializableStructure.ExportYAML(IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\Assembly\Serializable\SerializableStructure.cs:line 49
   at AssetRipper.Core.Classes.MonoBehaviour.ExportYAMLRoot(IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\MonoBehaviour.cs:line 88
   at AssetRipper.Core.UnityObjectBase.ExportYAMLDocument(IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\UnityObjectBase.cs:line 40
   at AssetRipper.Core.Project.Exporters.YamlExporterBase.Export(IExportContainer container, IEnumerable`1 assets, String path) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Exporters\YamlExporterBase.cs:line 58
   at AssetRipper.Core.Project.Collections.AssetExportCollection.Export(IProjectAssetContainer container, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Collections\AssetExportCollection.cs:line 40
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Project\ProjectExporterBase.cs:line 146
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Project\ProjectExporterBase.cs:line 66
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Export(CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 91
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, IEnumerable`1 assets) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 131
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 119
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIExportManager.cs:line 46

**Comment by ds5678** [comment]
No, we purposefully catch the exceptions and remain running so that users can see the error.
