### ISSUE TITLE
[Bug]: Model looks strange after import affects all assets I have tested

### ISSUE THREAD

**Issue by stayandwait** [ds5678/AssetRipper#171]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

Unity 2019.4.31f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

After I imported my asset I see this. Everything looks inverted. It's the same issue no matter what asset I use. How do I fix this?
![image](https://user-images.githubusercontent.com/15825041/142139899-ecae02f1-3fe2-40eb-8ce9-346c0592b88d.png)

### Relevant log output

System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.19043.0
System : Operating System: Windows x64
System : AssetRipper Version: 0.1.8.1
System : AssetRipper Build Type: Release x64 Published
System : Current UTC Time: 11/17/2021 5:10:05 AM
System : Loading locale en_US.json
: Language English (United Kingdom) isActive False
: Language English (United States) isActive True
: Language español isActive False
: Language Indonesia isActive False
: Language italiano isActive False
: Language português (Brasil) isActive False
: Language 中文（简体） isActive False
System : Available languages: en_GB, en_US, es, id, it, pt_BR, zh_Hans
General : Attempting to read files from C:\Users\Matthew\Desktop\avatar-Riding hood.vrca
Import : Game file 'avatar-Riding hood.vrca' has been found
Import : Mixed game structure has been found for 1 path(s)
Import : Files use the 'Unknown' scripting backend.
General : Finished reading files
General : About to begin export to C:\Users\Matthew\Desktop\avatar-Riding hood.vrca
General : Removing any files from a previous export...
Export : Attempting to export assets to C:\Users\Matthew\Desktop\avatar-Riding hood.vrca...
Export : Starting pre-export
Export : Starting export
Export : Exporting to Unity version 2017.3.0f3
Export : Preparing for export...
Export : Preparation complete. Starting to export now...
[Error] : System.IO.IOException: Cannot create 'C:\Users\Matthew\Desktop\avatar-Riding hood.vrca' because a file or directory with the same name already exists.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at AssetRipper.Core.Utils.DirectoryUtils.CreateVirtualDirectory(String path) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Utils\DirectoryUtils.cs:line 13
   at AssetRipper.Core.Project.Collections.AssetExportCollection.Export(IProjectAssetContainer container, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Collections\AssetExportCollection.cs:line 58
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Project\ProjectExporterBase.cs:line 146
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Project\ProjectExporterBase.cs:line 66
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Export(CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 91
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, IEnumerable`1 assets) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 131
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 119
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIExportManager.cs:line 46

General : About to begin export to D:\Software\Unity\MMD pmx avatars\Ripped Avatars\Ripped Model Files\avatar-Riding hood.vrca
General : Removing any files from a previous export...
Export : Attempting to export assets to D:\Software\Unity\MMD pmx avatars\Ripped Avatars\Ripped Model Files\avatar-Riding hood.vrca...
Export : Starting pre-export
Export : Starting export
Export : Exporting to Unity version 2017.3.0f3
Export : Preparing for export...
Export : Preparing for export...
Export : Preparation complete. Starting to export now...
Export : Preparation complete. Starting to export now...
ExportedFile : 'Prefab' exported
ExportedFile : 'face(Material)' exported
ExportedFile : 'cc (10)(Material)' exported
ExportedFile : 'cc (2)(Material)' exported
ExportedFile : 'undie(Material)' exported
ExportedFile : 'cc (9)(Material)' exported
ExportedFile : 'cc (10)(Texture2D)' exported
ExportedFile : 'body01(Material)' exported
ExportedFile : 'face(Texture2D)' exported
ExportedFile : 'cc (5)(Material)' exported
ExportedFile : 'hair01(Texture2D)' exported
ExportedFile : 'cc (1)(Texture2D)' exported
ExportedFile : 'CubedParadox/Flat Lit Toon(Shader)' exported
ExportedFile : 'cc (6)(Material)' exported
ExportedFile : 'hair03(Texture2D)' exported
ExportedFile : 'cc (3)(Material)' exported
ExportedFile : 'body01(Texture2D)' exported
ExportedFile : 'cc (2)(Texture2D)' exported
ExportedFile : 'cc (3)(Texture2D)' exported
ExportedFile : 'cc (8)(Texture2D)' exported
ExportedFile : 'cc (5)(Texture2D)' exported
ExportedFile : 'MikuHoodAvatar(Avatar)' exported
ExportedFile : 'hair01(Material)' exported
ExportedFile : 'cc (9)(Texture2D)' exported
ExportedFile : 'cc (6)(Texture2D)' exported
ExportedFile : 'cc (8)(Material)' exported
ExportedFile : 'New(Material)' exported
ExportedFile : 'cc (1)(Material)' exported
ExportedFile : 'Body(Mesh)' exported
ExportedFile : 'hair03(Material)' exported
Export : Finished exporting assets
Export : Finished post-export
General : Export Complete!

**Comment by stayandwait** [comment]
Also these are my shaders are they look correct. What am I doing wrong? 
![image](https://user-images.githubusercontent.com/15825041/142140395-c6ca89d2-8c1c-4a1c-957d-6b9876383609.png
here is the log again
[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7552002/AssetRipper.log)
)

**Comment by stayandwait** [comment]
Here is one of the shaders expanded
![image](https://user-images.githubusercontent.com/15825041/142140537-c40249db-a1d9-447e-93d8-63548cd17900.png)

**Comment by ds5678** [comment]
We don't offer technical support for ripping VR Chat avatars.
