### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by KrevetkaOo** [ds5678/AssetRipper#25]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

unity 2019.4.29f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

wanted to unpack the .vrca file

### Relevant log output

```
Game name: (please, specify the game name)
Engine version: (specify engine version, if known)
Platform: (specify platform, if known)

Error message: Some data left

Stack trace:    at AssetRipper.Core.Lz4.Lz4DecodeStream.ReadBuffer(Stream stream, Int64 count) in E:\repos\AssetRipper\AssetRipperCore\Lz4\Lz4DecodeStream.cs:line 225
   at AssetRipper.Core.Parser.Files.BundleFile.IO.BundleFileBlockReader.ReadEntry(Node entry) in E:\repos\AssetRipper\AssetRipperCore\Parser\Files\BundleFile\IO\BundleFileBlockReader.cs:line 90
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadFileStreamData(Stream stream, Int64 basePosition, Int64 headerSize) in E:\repos\AssetRipper\AssetRipperCore\Parser\Files\BundleFile\BundleFileScheme.cs:line 210
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream) in E:\repos\AssetRipper\AssetRipperCore\Parser\Files\BundleFile\BundleFileScheme.cs:line 64
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream, String filePath, String fileName) in E:\repos\AssetRipper\AssetRipperCore\Parser\Files\BundleFile\BundleFileScheme.cs:line 34
   at AssetRipper.Core.Structure.SchemeReader.ReadScheme(SmartStream stream, String filePath, String fileName) in E:\repos\AssetRipper\AssetRipperCore\Structure\SchemeReader.cs:line 51
   at AssetRipper.Core.Structure.SchemeReader.LoadScheme(String filePath, String fileName) in E:\repos\AssetRipper\AssetRipperCore\Structure\SchemeReader.cs:line 19
   at AssetRipper.Core.Structure.GameStructure.GameStructure.ProcessPlatformStructure(GameStructureProcessor processor, PlatformGameStructure structure) in E:\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 176
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, LayoutInfo layinfo) in E:\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 59
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, LayoutInfo layinfo) in E:\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 37
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths) in E:\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 26
   at AssetRipper.GUI.MainWindow.LoadFiles(Object data) in E:\repos\AssetRipper\AssetRipperGUI\MainWindow.xaml.cs:line 98
```

**Comment by ds5678** [comment]
Hello, this is a known issue (#5). We are actively working on it right now.

**Comment by ds5678** [comment]
Unless you have the same stack trace, please post a new issue.

**Comment by KrevetkaOo** [comment]
the problem remains exactly the same, nothing has changed :(

**Comment by ds5678** [comment]
Do you have a file I can test with?

**Comment by KrevetkaOo** [comment]
I can't upload this file here, so I used a file hosting service: https://dropmefiles.com/tAaui

**Comment by ds5678** [comment]
I was recently informed by another VR Chat user that this problem is unrelated to AssetRipper and is caused by game-specific protections.
