### ISSUE TITLE
[Bug]: Vrchat data ripping error

### ISSUE THREAD

**Issue by meeth531** [ds5678/AssetRipper#27]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2019.4.29f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

I'm trying to rip the Vrchat avatar file, but I get an error.
Since Vrchat is now in Unity 2019, I'm getting errors.
Files that cannot be ripped:
[Uploading __data.zip…]()

### Relevant log output

Game name: (VRChat)
Engine version: (Unity2019.4.29f1)
Platform: (Windows x64)

Error message: Some data left

Stack trace:    at AssetRipper.Core.Lz4.Lz4DecodeStream.ReadBuffer(Stream stream, Int64 count) in E:\repos\AssetRipper\AssetRipperCore\Lz4\Lz4DecodeStream.cs:line 225
   at AssetRipper.Core.Parser.Files.BundleFile.IO.BundleFileBlockReader.ReadEntry(Node entry) in E:\repos\AssetRipper\AssetRipperCore\Parser\Files\BundleFile\IO\BundleFileBlockReader.cs:line 90
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadFileStreamData(Stream stream, Int64 basePosition, Int64 headerSize) in E:\repos\AssetRipper\AssetRipperCore\Parser\Files\BundleFile\BundleFileScheme.cs:line 210
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream) in E:\repos\AssetRipper\AssetRipperCore\Parser\Files\BundleFile\BundleFileScheme.cs:line 64
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream, String filePath, String fileName) in E:\repos\AssetRipper\AssetRipperCore\Parser\Files\BundleFile\BundleFileScheme.cs:line 34
   at AssetRipper.Core.Structure.SchemeReader.ReadScheme(SmartStream stream, String filePath, String fileName) in E:\repos\AssetRipper\AssetRipperCore\Structure\SchemeReader.cs:line 51
   at AssetRipper.Core.Structure.SchemeReader.LoadScheme(String filePath, String fileName) in E:\repos\AssetRipper\AssetRipperCore\Structure\SchemeReader.cs:line 19
   at AssetRipper.Core.Structure.GameStructure.GameStructure.ProcessPlatformStructure(GameStructureProcessor processor, PlatformGameStructure structure) in E:\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 176
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, LayoutInfo layinfo) in E:\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 59
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, LayoutInfo layinfo) in E:\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 37
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths) in E:\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 26
   at AssetRipper.GUI.MainWindow.LoadFiles(Object data) in E:\repos\AssetRipper\AssetRipperGUI\MainWindow.xaml.cs:line 98

**Comment by meeth531** [comment]
Files that cannot be ripped:
[__data.zip](https://github.com/ds5678/AssetRipper/files/6961758/__data.zip)

**Comment by ds5678** [comment]
This should have been resolved in a recent commit. If your problem persists, please post a new issue.
