### ISSUE TITLE
[Bug]:  Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il

### ISSUE THREAD

**Issue by afzaale01** [ds5678/AssetRipper#31]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

 Not sure

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

Game name: (please, specify the game name)
Engine version: (specify engine version, if known)
Platform: (specify platform, if known)

Error message: Fatal Exception initializing LibCpp2IL!

Stack trace:    at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses)
   at AssetRipper.Core.Structure.Assembly.Managers.Il2CppManager.Initialize(PlatformGameStructure gameStructure) in C:\Users\Jeremy\source\repos\AssetRipper\AssetRipperCore\Structure\Assembly\Managers\Il2CppManager.cs:line 24
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, LayoutInfo layinfo) in C:\Users\Jeremy\source\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 85
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, LayoutInfo layinfo) in C:\Users\Jeremy\source\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 36
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths) in C:\Users\Jeremy\source\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 26
   at AssetRipper.GUI.MainWindow.LoadFiles(Object data) in C:\Users\Jeremy\source\repos\AssetRipper\AssetRipperGUI\MainWindow.xaml.cs:line 98

**Comment by ds5678** [comment]
Can you upload your `AssetRipper.log` file? It's in the same folder as the exe.
