### ISSUE TITLE
[Bug]: Crashes on Unity 2020 + and some 2019 games

### ISSUE THREAD

**Issue by ds5678** [ds5678/AssetRipper#5]
### Are you on the latest version of AssetRipper?

- [X] Yes, I'm on the latest version of AssetRipper.

### Which release are you using?

Not Applicable

### Which game did this occur on?

This bug occurs on Unity 2020+ games. 

It can also occur on Unity 2019 games if the developer has the Addressable system enabled.

### Describe the issue.

This bug occurs because AssetRipper has not yet implemented support for the Addressable system.

### Relevant log output

Stack traces for this bug usually look similar to this:

```
General [Error]: System.Exception: Some data left
   at AssetRipper.Lz4.Lz4DecodeStream.ReadBuffer(Stream stream, Int64 count) in E:\repos\AssetRipper\AssetRipperCore\Lz4\Lz4DecodeStream.cs:line 233
   at AssetRipper.Parser.Files.BundleFile.BundleFileScheme.ReadFileStreamMetadata(Stream stream, Int64 basePosition) in E:\repos\AssetRipper\AssetRipperCore\Parser\Files\BundleFile\BundleFileScheme.cs:line 160
   at AssetRipper.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream) in E:\repos\AssetRipper\AssetRipperCore\Parser\Files\BundleFile\BundleFileScheme.cs:line 66
   at AssetRipper.Structure.GameCollection.ReadScheme(SmartStream stream, String filePath, String fileName) in E:\repos\AssetRipper\AssetRipperCore\Structure\GameCollection.cs:line 119
   at AssetRipper.Structure.GameCollection.LoadScheme(String filePath, String fileName) in E:\repos\AssetRipper\AssetRipperCore\Structure\GameCollection.cs:line 75
   at AssetRipper.Structure.GameStructure.GameStructure.ProcessPlatformStructure(GameStructureProcessor processor, PlatformGameStructure structure) in E:\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 325
   at AssetRipper.Structure.GameStructure.GameStructure.Load(List`1 paths, LayoutInfo layinfo) in E:\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 139
   at AssetRipper.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, LayoutInfo layinfo) in E:\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 38
   at AssetRipper.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths) in E:\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 26
   at AssetRipperLibrary.Ripper.Load(IReadOnlyList`1 paths) in E:\repos\AssetRipper\AssetRipperLibrary\Ripper.cs:line 21
   at UnitTester.Program.RunTests() in E:\repos\AssetRipper\UnitTester\Program.cs:line 65
```

**Comment by ds5678** [comment]
Through various pull requests and commits, this should be resolved. Please post any problems as new issues.
