### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ramz0n** [ds5678/AssetRipper#53]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Console Version Windows x64

### Which Unity version did this occur on?

2020.3.0f2

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Couldn't uncompile any file

### Relevant log output

```
Import : Files use the 'Unknown' scripting backend.
General : SerializedFileException: v:2020.3.3f1 p:StandaloneWin64Player t:Shader n:unity default resources
Path:Resources\unity default resources
Message: Error during reading of asset type Shader
Inner: System.Exception: End of stream. Read 2414746, expected 318799111 elements
   at AssetRipper.Core.IO.Endian.EndianReader.ReadUInt16Array()
   at AssetRipper.Core.Classes.Shader.SerializedShader.SerializedSubProgram.Read(AssetReader reader)
   at AssetRipper.Core.IO.Asset.AssetReader.ReadAssetArray[T]()
   at AssetRipper.Core.Classes.Shader.SerializedShader.SerializedProgram.Read(AssetReader reader)
   at AssetRipper.Core.Classes.Shader.SerializedShader.SerializedPass.Read(AssetReader reader)
   at AssetRipper.Core.IO.Asset.AssetReader.ReadAssetArray[T]()
   at AssetRipper.Core.IO.Asset.AssetReader.ReadAssetArray[T]()
   at AssetRipper.Core.Classes.Shader.SerializedShader.SerializedShader.Read(AssetReader reader)
   at AssetRipper.Core.Classes.Shader.Shader.Read(AssetReader reader)
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size)
StackTrace:    at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size)
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, ObjectInfo& info)
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadData(Stream stream)
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file)
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file)
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file)
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadSerializedFiles()
   at AssetRipper.Core.Structure.GameStructure.GameStructureProcessor.ProcessSchemes(GameCollection fileCollection)
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, LayoutInfo layinfo)
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, LayoutInfo layinfo)
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths)
   at AssetRipper.Library.Ripper.Load(IReadOnlyList`1 paths)
   at AssetRipper.Console.Program.Run(Options options)


```

**Comment by ds5678** [comment]
I think this should be fixed on the latest alpha build

**Comment by ramz0n** [comment]
where can i get the alpha build?

**Comment by ds5678** [comment]
<https://github.com/ds5678/AssetRipper/actions>

**Comment by ramz0n** [comment]
thanks bud it works now nice job
