### ISSUE TITLE
[Bug]: Doesnt Load Uncompressed bundles

### ISSUE THREAD

**Issue by NabsiYa** [ds5678/AssetRipper#73]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2019.4.29f1

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

i used https://github.com/Perfare/AssetStudio which sucessfully ripped the assets from the bundle but didnt include scenes so i though this one would work but it greeted with me message "Some data" when trying to decompile my bundle has no compression to begin but the program thinks it has compression which causes this issue.

### Relevant log output

![image](https://user-images.githubusercontent.com/43046474/131907326-b152c9af-2edf-41e9-b811-333b96f201db.png)

**Comment by ds5678** [comment]
I'll need your `AssetRipper.log` file. It's in the same folder as the exe.

**Comment by NabsiYa** [comment]
`System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.17134.0
System : Operating System: Windows x64
System : AssetRipper Version: 0.1.5.2
System : AssetRipper Build Type: Release x64 Published
System : Current UTC Time: 9/3/2021 1:59:21 PM
General : Attempting to read files from C:\Users\Administrator\Desktop\bundle.unity3d
Import : Game file 'bundle.unity3d' has been found
Import : Mixed game structure has been found for 1 path(s)
[Error] : System.Exception: Some data left
   at AssetRipper.Core.Lz4.Lz4DecodeStream.ReadBuffer(Stream stream, Int64 count) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Lz4/Lz4DecodeStream.cs:line 225
   at AssetRipper.Core.Parser.Files.BundleFile.IO.BundleFileBlockReader.ReadEntry(Node entry) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Parser/Files/BundleFile/IO/BundleFileBlockReader.cs:line 90
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadFileStreamData(Stream stream, Int64 basePosition, Int64 headerSize) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Parser/Files/BundleFile/BundleFileScheme.cs:line 210
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Parser/Files/BundleFile/BundleFileScheme.cs:line 60
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream, String filePath, String fileName) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Parser/Files/BundleFile/BundleFileScheme.cs:line 40
   at AssetRipper.Core.Structure.SchemeReader.ReadScheme(SmartStream stream, String filePath, String fileName) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/SchemeReader.cs:line 51
   at AssetRipper.Core.Structure.SchemeReader.LoadScheme(String filePath, String fileName) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/SchemeReader.cs:line 19
   at AssetRipper.Core.Structure.GameStructure.GameStructure.ProcessPlatformStructure(GameStructureProcessor processor, PlatformGameStructure structure) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/GameStructure/GameStructure.cs:line 127
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/GameStructure/GameStructure.cs:line 65
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/GameStructure/GameStructure.cs:line 46
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/GameStructure/GameStructure.cs:line 38
   at AssetRipper.Library.Ripper.Load(IReadOnlyList`1 paths) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperLibrary/Ripper.cs:line 31
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperGUI/Managers/UIImportManager.cs:line 24

`

**Comment by NabsiYa** [comment]
[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7106397/AssetRipper.log)

**Comment by ds5678** [comment]
Although I cannot know for sure just from the stack trace, this appears to be an encrypted/protected bundle.
