### ISSUE TITLE
[Bug]: GUI Selected Asset Null Reference Exception

### ISSUE THREAD

**Issue by nopa607** [ds5678/AssetRipper#82]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2018

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

i can successfully load a AB, and i can see many assets in it;
this is the situation:
i try to find AnimatorControllers that used by Animator; 
when i open a Animator;
GUI report ERROR:
![image](https://user-images.githubusercontent.com/54985153/133057450-ee0cbd06-77a3-4519-b0f3-b4b955a4c7b2.png)

### Relevant log output

17:08:15: [Error] : System.NullReferenceException: Object reference not set to an instance of an object.
   at AssetRipper.Core.Classes.AnimatorController.AnimatorController.ExportYAMLRoot(IExportContainer container) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Classes/AnimatorController/AnimatorController.cs:line 171
   at AssetRipper.Core.Classes.Object.Object.ExportYAML(IExportContainer container) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Classes/Object/Object.cs:line 80
   at AssetRipper.GUI.AssetInfo.SelectedAsset.BuildYamlTree() in /home/runner/work/AssetRipper/AssetRipper/AssetRipperGUI/AssetInfo/SelectedAsset.cs:line 108

**Comment by nopa607** [comment]
> Thank you for submitting your first issue here. Please be sure you have uploaded your `AssetRipper.log` file. It is in the same folder as the exe file. :)

[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7153106/AssetRipper.log)

**Comment by ds5678** [comment]
Are you legally able to give me a bundle that causes this issue? I can't solve this particular problem without one.

**Comment by nopa607** [comment]
> Are you legally able to give me a bundle that causes this issue? I can't solve this particular problem without one.

[AssetBundles.zip](https://github.com/ds5678/AssetRipper/files/7174375/AssetBundles.zip)
